### PR TITLE
terminate() function

### PR DESCRIPTION
**Pull request by brucedjones**
Allows you to terminate a running python script.

### CODE REVIEW

**Comment by Almenon** [comment]
I like it!

But kill alone may not suffice for exiting the script.  There should be a paramater in the function that lets you send a kill signal like SIGKILL

Example: https://github.com/Almenon/AREPL-backend/blob/master/index.js#L78

Though if you kill via signal you might also want to fix the close event functionality https://github.com/extrabacon/python-shell/issues/94

**Comment by eman6576** [comment]
Could this be merged anytime soon? I actually need this functionality in a project that I am working on. 😀

**Comment by brucedjones** [comment]
So I added the ability to send a kill signal. One thing that was not clear to me, was why terminate should occur if both stderr and stdout are closed, the main thing we care about is the process itself ending. So I removed that functionality as it seemed like unnecessary extra complication.

**Comment by brucedjones** [comment]
So in fixing the bugs I put the ending on stderr and stdout back in. I figured it better to be consistent with previous behavior.

**Comment by brucedjones** [comment]
@extrabacon any objections to this pull request?

**Comment by extrabacon** [comment]
Not at all, I just want to make sure I can publish shortly after merging. So sorry, too much work means I don't have time to properly handle this project.

**Comment by Almenon** [comment]
@extrabacon maybe someone could be added as a maintainer?  I wouldn't mind helping out with the project.  Or maybe @brucedjones?

**Comment by extrabacon** [comment]
@brucedjones + @Almenon: you are now collaborators on the repo
@brucedjones: you can also publish to NPM

**Comment by Almenon** [comment]
Thanks extrabacon.  I guess I'll start out by taking a look at the unit tests.  @brucedjones, want to merge in your pull request?

**Comment by Almenon** [comment]
@brucedjones I'm looking for a new maintainer to take on my duties, are you still up for it?

**Pull request merged**
